config/routes.rb
Rails.application.routes.draw do
  resources :moods
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mood.rb
class Mood < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: [:show, :edit, :update, :destroy]

  # GET /moods
  # GET /moods.json
  def index
    @moods = Mood.all
  end

  # GET /moods/1
  # GET /moods/1.json
  def show
  end

  # GET /moods/new
  def new
    @mood = Mood.new
  end

  # GET /moods/1/edit
  def edit
  end

  # POST /moods
  # POST /moods.json
  def create
    @mood = Mood.new(mood_params)

    respond_to do |format|
      if @mood.save
        format.html { redirect_to @mood, notice: 'Mood was successfully created.' }
        format.json { render :show, status: :created, location: @mood }
      else
        format.html { render :new }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moods/1
  # PATCH/PUT /moods/1.json
  def update
    respond_to do |format|
      if @mood.update(mood_params)
        format.html { redirect_to @mood, notice: 'Mood was successfully updated.' }
        format.json { render :show, status: :ok, location: @mood }
      else
        format.html { render :edit }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moods/1
  # DELETE /moods/1.json
  def destroy
    @mood.destroy
    respond_to do |format|
      format.html { redirect_to moods_url, notice: 'Mood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mood
      @mood = Mood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mood_params
      params.require(:mood).permit(:short, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoodTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moods/_form.html.haml
= form_for @mood do |f|
  - if @mood.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mood.errors.count, "error")} prohibited this mood from being saved:"
      %ul
        - @mood.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :short
    = f.text_field :short
  .field
    = f.label :note
    = f.text_area :note
  .actions
    = f.submit 'Save'

app/views/moods/edit.html.haml
%h1 Editing mood

= render 'form'

= link_to 'Show', @mood
\|
= link_to 'Back', moods_path

app/views/moods/index.html.haml
%h1 Listing moods

%table
  %thead
    %tr
      %th Short
      %th Note
      %th
      %th
      %th

  %tbody
    - @moods.each do |mood|
      %tr
        %td= mood.short
        %td= mood.note
        %td= link_to 'Show', mood
        %td= link_to 'Edit', edit_mood_path(mood)
        %td= link_to 'Destroy', mood, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Mood', new_mood_path

app/views/moods/new.html.haml
%h1 New mood

= render 'form'

= link_to 'Back', moods_path

app/views/moods/show.html.haml
%p#notice= notice

%p
  %b Short:
  = @mood.short
%p
  %b Note:
  = @mood.note

= link_to 'Edit', edit_mood_path(@mood)
\|
= link_to 'Back', moods_path